# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46a708130bbb354717b50118aca25019945f27482858436be8198dd697fb678252c336f2c003b511a161fb2741a87caaab9bf5b44e9c4aae57b94df3244d7af

test:
  secret_key_base: 88d48b90bd67c22b095e4df921192889e0a1422502e61800863ba8c4a29bb607ceb64dc4f6273aea6aaed28fb7e59487015572f37baddba2d87263771b73e40b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
